### ISSUE TITLE
Calibrating the camera using binned images crops the rectified image

### ISSUE THREAD

**Issue by joaopsousa99** [basler/pylon-ros-camera#143]
I calibrated a Basler daA2500-14uc camera with 2x2 binning and the resulting calibration file is the following:

```yaml
image_width: 1296
image_height: 972
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1874.63171,    0.     ,  647.5    ,
            0.     , 1879.55762,  485.5    ,
            0.     ,    0.     ,    1.     ]
distortion_model: rational_polynomial
distortion_coefficients:
  rows: 1
  cols: 8
  data: [-13.238113, -98.012135, 0.001444, 0.002849, 1357.782415, -13.050801, -102.363353, 1383.055291]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1854.37744,    0.     ,  648.98589,    0.     ,
            0.     , 1863.35327,  485.55316,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
```

However, when I run `roslaunch pylon_camera pylon_camera_node.launch`, the resulting rectified image is cropped to the top left quarter of the image. The same happens when I calibrate the camera with 4x4 binning and run the driver with the same binning, except it's the top left sixteenth of the image.

Thus, I think the driver is somehow dividing both the width and the height of the image by the binning amount.

I found a temporary solution: setting `image_width` and `image_height` to the full resolution values.

Is this a bug or an intended feature. I managed to find a workaround but I think I should report the issue all the same.
