### ISSUE TITLE
Can't set camera parameters by default.yaml file (a2A3840-13gcPRO)

### ISSUE THREAD

**Issue by RCdataset** [basler/pylon-ros-camera#273]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

Hi, first of all, thank you for sharing great driver.
I am trying to run Basler a2A3840-13gcPRO camera by this driver. But I got some trouble shooting here. 

**Is your camera operational with the Basler pylon Viewer on your platform?** -> Yes
And I also successfully built the ROS2 driver.

However, when I run the launch file by command 'ros2 launch pylon_ros2_camera_wrapper pylon_ros2_camera.launch.py', I got error.

`
Found camera device! Device Model : a2A3840-13gcPRO with Device User ID : pis
[ERROR] Error applying camera specific startup setting for gigE cameras: Value 1000000.000000 must be smaller than or equal 999999.000000
[ERROR] Error applying camera specific startup setting for gigE cameras (e.g., mtu size for gigE ...) to the camera!
[ERROR] Error when trying to init and register. Shutting down now.
`

Here is my 'default.yaml' file. 
```
# Camera parameters

/**:
  ros__parameters:

    #  The tf frame under which the images were published
    camera_frame: pylon_camera

    #  The DeviceUserID of the camera. If empty, the first camera found in the
    #  device list will be used
    device_user_id: "pis"

    #  The CameraInfo URL (Uniform Resource Locator) where the optional intrinsic
    #  camera calibration parameters are stored. This URL string will be parsed
    #  from the ROS-CameraInfoManager:
    camera_info_url: ""
    # camera_info_url: package://pylon_ros2_camera_wrapper/config/camera_calibration.yaml

    #  The encoding of the pixels -- channel meaning, ordering, size
    #  taken from the list of strings in include/sensor_msgs/image_encodings.h
    #  The supported encodings are 'mono8', 'bgr8', 'rgb8', 'bayer_bggr8',
    #  'bayer_gbrg8' and 'bayer_rggb8'
    #  Default values are 'mono8' and 'rgb8'
    image_encoding: 'rgb8'

    #  Binning factor to get downsampled images. It refers here to any camera
    #  setting which combines rectangular neighborhoods of pixels into larger
    #  "super-pixels." It reduces the resolution of the output image to
    #  (width / binning_x) x (height / binning_y).
    #  The default values binning_x = binning_y = 0 are considered the same
    #  as binning_x = binning_y = 1 (no subsampling).
    binning_x: 1
    binning_y: 1

    #  The desired publisher frame rate if listening to the topics.
    #  This parameter can only be set once at startup.
    #  Calling the GrabImages-Action can result in a higher framerate.
    #  The maximum possible frame rate is displayed when starting the driver.
    frame_rate: 10.0

    #  Mode of camera's shutter.
    #  The supported modes are "rolling", "global" and "global_reset"
    #  Default value is "" (empty) means default_shutter_mode
    shutter_mode: "global"

    ##########################################################################
    ######################## Image Intensity Settings ########################
    ##########################################################################
    # The following settings do *NOT* have to be set. Each camera has default
    # values which provide an automatic image adjustment resulting in valid
    # images
    ##########################################################################

    #  The exposure time in microseconds to be set after opening the camera.
    # exposure: 1000.0

    #  The target gain in percent of the maximal value the camera supports
    #  For USB cameras, the gain is in dB, for GigE cameras it is given in so
    #  called 'device specific units'.
    # gain: 0.5

    #  Gamma correction of pixel intensity.
    #  Adjusts the brightness of the pixel values output by the camera's sensor
    #  to account for a non-linearity in the human perception of brightness or
    #  of the display system (such as CRT).
    # gamma: 1.0

    #  The average intensity value of the images
    #  It depends on the exposure time as well as the gain setting. 
    #  If 'exposure' is provided, the interface will
    #  try to reach the desired brightness by only varying the gain. (What may
    #  often fail, because the range of possible exposure values is many
    #  times higher than the gain range). If 'gain' is provided, the interface will
    #  try to reach the desired brightness by only varying the exposure time. If
    #  gain AND exposure are given, it is not possible to reach the brightness,
    #  because both are assumed to be fixed.
    # brightness: 100

    #  Only relevant, if 'brightness' is set
    #  The brightness_continuous flag controls the auto brightness function.
    #  If it is set to false, the brightness will only be reached once.
    #  Hence changing light conditions lead to changing brightness values.
    #  If it is set to true, the given brightness will be reached continuously,
    #  trying to adapt to changing light conditions. This is only possible for
    #  values in the possible auto range of the pylon API which is generally [50 - 205].
    # brightness_continuous: true

    #  Only relevant, if 'brightness' is set
    #  If the camera should try to reach and / or keep the brightness, hence
    #  adapting to changing light conditions, at least one of the following flags
    #  must be set.
    #  If both are set, the interface will use the profile that tries to keep the
    #  gain at minimum to reduce white noise.
    #  The exposure_auto flag indicates, that the desired brightness will be
    #  reached by adapting the exposure time.
    #  The gain_auto flag indicates, that the desired brightness will be
    #  reached by adapting the gain.
    # exposure_auto: true
    # gain_auto: true

    ##########################################################################

    #  The timeout while searching the exposure which is connected to the
    #  desired brightness. For slow system this has to be increased.
    # exposure_search_timeout: 5.0

    #  The exposure search can be limited with an upper bound. This is to prevent
    #  very high exposure times and resulting timeouts.
    #  A typical value for this upper bound is ~2000000us.
    #  Beware that this upper limit is only set if `startup_user_set` is set to `Default`.
    # auto_exposure_upper_limit: 2000000.0

    #  The MTU size. Only used for GigE cameras.
    #  To prevent lost frames configure the camera has to be configured
    #  with the MTU size the network card supports. A value greater 3000
    #  should be good (1500 for single-board computer)
    gige:
     mtu_size: 3000

    #  Only used for GigE cameras.
    #  The inter-package delay in ticks to prevent lost frames.
    #  For most of GigE cameras, a value of 1000 is reasonable.
    #  For cameras used on a single-board computer this value should be set to 11772.
    gige:
     inter_pkg_delay: 1000

    #  Only used for GigE cameras.
    #  The frame transmission delay in ticks.
    #  In most cases, this parameter should be set to 0.
    #  However, if your network hardware can't handle spikes in network traffic
    #  (e.g., if you are triggering multiple camera simultaneously),
    #  you can use the frame transmission delay parameter to stagger the
    #  start of image data transmissions from each camera.
    gige:
     frame_transmission_delay: 0
```

And setting **'startup_user_set:=Default'**, it doesn't work with same above reason.

When I ran the launch file by command 'ros2 launch pylon_ros2_camera_wrapper pylon_ros2_camera.launch.py **startup_user_set:=UserSet2'**, It worked.

However the received images by ros topic seemed mono8 and under 5Hz.
It's totally different setting with my 'default.yaml' file, and I think it can't load my default.yaml file.
And I tried to change camera parameters by ROS service call command, but changable camera parameters are limited (The camera frame rates couldn't be changed).

And I tried another Basler camera (acA1300-30gm), it worked with 'ros2 launch pylon_ros2_camera_wrapper pylon_ros2_camera.launch.py' command, but it also looks like it can't read my default.yaml file. 

How can I run Basler camera (a2A3840-13gcPRO) by default.yaml file setting? Please help.
The camera model a2A3840-13gcPRO is not supported yet?
Or did I something wrong when setting environment?

Thank you.

### Hardware setup description

Basler a2A3840-13gcPRO 
PC : CPU architecture X86_64
Interfaces : GigE

### Runtime information

```shell
Pylon 8.1.0
Pylon-supplementary 1.7.2
ROS2 Humble
Ubuntu 22.04
```

### Is your camera operational with the Basler pylon Viewer on your platform?

Yes
